//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoTransmitter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoTransmitter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto discovery.
        /// </summary>
        public static string Autodiscovery {
            get {
                return ResourceManager.GetString("Autodiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string BitrateAuto {
            get {
                return ResourceManager.GetString("BitrateAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate must be in range between 1 and 25.
        /// </summary>
        public static string BitrateError {
            get {
                return ResourceManager.GetString("BitrateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string BitrateManual {
            get {
                return ResourceManager.GetString("BitrateManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate.
        /// </summary>
        public static string BitrateText {
            get {
                return ResourceManager.GetString("BitrateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbit/s.
        /// </summary>
        public static string BitrateTextMbit {
            get {
                return ResourceManager.GetString("BitrateTextMbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string Connectionfailed {
            get {
                return ResourceManager.GetString("Connectionfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed to VideoServer, ready to start new.
        /// </summary>
        public static string ConnectionfailedtoVideoServer {
            get {
                return ResourceManager.GetString("ConnectionfailedtoVideoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom video source.
        /// </summary>
        public static string CustomVideoSourceHeader {
            get {
                return ResourceManager.GetString("CustomVideoSourceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri.
        /// </summary>
        public static string CustomVideoSourceUri {
            get {
                return ResourceManager.GetString("CustomVideoSourceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct IP.
        /// </summary>
        public static string DirectIP {
            get {
                return ResourceManager.GetString("DirectIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close application?.
        /// </summary>
        public static string Doyouwanttocloseapplication {
            get {
                return ResourceManager.GetString("Doyouwanttocloseapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle is offline.
        /// </summary>
        public static string DroneOffline {
            get {
                return ResourceManager.GetString("DroneOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable hardware decoding.
        /// </summary>
        public static string Enablehardwaredecoding {
            get {
                return ResourceManager.GetString("Enablehardwaredecoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail number could not be empty string..
        /// </summary>
        public static string ErrorTail {
            get {
                return ResourceManager.GetString("ErrorTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load video from {0}.
        /// </summary>
        public static string Failedtoloadvideofrom {
            get {
                return ResourceManager.GetString("Failedtoloadvideofrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start stream to VideoServer.
        /// </summary>
        public static string FailedtostartstreamtoVideoServer {
            get {
                return ResourceManager.GetString("FailedtostartstreamtoVideoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid custom video source URI: The format of the URI could not be determined..
        /// </summary>
        public static string InvalidCustomVideoSourceURI {
            get {
                return ResourceManager.GetString("InvalidCustomVideoSourceURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading video.
        /// </summary>
        public static string Loadingvideo {
            get {
                return ResourceManager.GetString("Loadingvideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Not selected&gt;.
        /// </summary>
        public static string Nodevice {
            get {
                return ResourceManager.GetString("Nodevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready.
        /// </summary>
        public static string Notreadytostream {
            get {
                return ResourceManager.GetString("Notreadytostream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Not selected&gt;.
        /// </summary>
        public static string Novehicle {
            get {
                return ResourceManager.GetString("Novehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Vehicles found.
        /// </summary>
        public static string NoVehiclesFound {
            get {
                return ResourceManager.GetString("NoVehiclesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Readytostream {
            get {
                return ResourceManager.GetString("Readytostream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to stream to VideoServer {0}.
        /// </summary>
        public static string ReadytostreamtoVideoServer {
            get {
                return ResourceManager.GetString("ReadytostreamtoVideoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting.
        /// </summary>
        public static string Reconnecting {
            get {
                return ResourceManager.GetString("Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting to VideoServer.
        /// </summary>
        public static string ReconnectingtoVideoServer {
            get {
                return ResourceManager.GetString("ReconnectingtoVideoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select telemetry source.
        /// </summary>
        public static string Selecttelemetrysource {
            get {
                return ResourceManager.GetString("Selecttelemetrysource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select video source.
        /// </summary>
        public static string Selectvideosource {
            get {
                return ResourceManager.GetString("Selectvideosource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for connecting to VideoServer and UgCS.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown confirmation.
        /// </summary>
        public static string Shutdownconfirmation {
            get {
                return ResourceManager.GetString("Shutdownconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start streaming.
        /// </summary>
        public static string StartStreaming {
            get {
                return ResourceManager.GetString("StartStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop streaming.
        /// </summary>
        public static string StopStreaming {
            get {
                return ResourceManager.GetString("StopStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream finished.
        /// </summary>
        public static string Streamfinished {
            get {
                return ResourceManager.GetString("Streamfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming.
        /// </summary>
        public static string Streaming {
            get {
                return ResourceManager.GetString("Streaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming to {0}.
        /// </summary>
        public static string StreamingTo {
            get {
                return ResourceManager.GetString("StreamingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream initializing.
        /// </summary>
        public static string Streaminitializing {
            get {
                return ResourceManager.GetString("Streaminitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry: .
        /// </summary>
        public static string TelemetryLabel {
            get {
                return ResourceManager.GetString("TelemetryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong UGCS IP address. Please provide correct IP..
        /// </summary>
        public static string UgcsIp {
            get {
                return ResourceManager.GetString("UgcsIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong UGCS port address. Please provide correct port..
        /// </summary>
        public static string UgcsPort {
            get {
                return ResourceManager.GetString("UgcsPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UgCS Server.
        /// </summary>
        public static string UgCSServer {
            get {
                return ResourceManager.GetString("UgCSServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UgCS Server is not connected.
        /// </summary>
        public static string UgCSServerisnotconnected {
            get {
                return ResourceManager.GetString("UgCSServerisnotconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UgCS Video Transmitter {0}.
        /// </summary>
        public static string UgCSVideoTransmitter {
            get {
                return ResourceManager.GetString("UgCSVideoTransmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle is not selected.
        /// </summary>
        public static string Vehicleisnotselected {
            get {
                return ResourceManager.GetString("Vehicleisnotselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video: .
        /// </summary>
        public static string VideoLabel {
            get {
                return ResourceManager.GetString("VideoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Server.
        /// </summary>
        public static string VideoServer {
            get {
                return ResourceManager.GetString("VideoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong VideoServer IP address. Please provide correct IP..
        /// </summary>
        public static string VideoServerIp {
            get {
                return ResourceManager.GetString("VideoServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoServer not discovered.
        /// </summary>
        public static string VideoServernotdiscovered {
            get {
                return ResourceManager.GetString("VideoServernotdiscovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong VideoServer port address. Please provide correct port..
        /// </summary>
        public static string VideoServerPort {
            get {
                return ResourceManager.GetString("VideoServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video source is not selected.
        /// </summary>
        public static string Videosourceisnotselected {
            get {
                return ResourceManager.GetString("Videosourceisnotselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video source is not streaming video.
        /// </summary>
        public static string Videosourceisnotstreamingvideo {
            get {
                return ResourceManager.GetString("Videosourceisnotstreamingvideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video source name.
        /// </summary>
        public static string Videosourcename {
            get {
                return ResourceManager.GetString("Videosourcename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video source not selected.
        /// </summary>
        public static string Videosourcenotselected {
            get {
                return ResourceManager.GetString("Videosourcenotselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video stopped from {0}.
        /// </summary>
        public static string Videostoppedfrom {
            get {
                return ResourceManager.GetString("Videostoppedfrom", resourceCulture);
            }
        }
    }
}
